#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KisiselBlog")]
	public partial class BlogDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEtiket(Etiket instance);
    partial void UpdateEtiket(Etiket instance);
    partial void DeleteEtiket(Etiket instance);
    partial void InsertEtiketMakale(EtiketMakale instance);
    partial void UpdateEtiketMakale(EtiketMakale instance);
    partial void DeleteEtiketMakale(EtiketMakale instance);
    partial void InsertIletisim(Iletisim instance);
    partial void UpdateIletisim(Iletisim instance);
    partial void DeleteIletisim(Iletisim instance);
    partial void InsertKategori(Kategori instance);
    partial void UpdateKategori(Kategori instance);
    partial void DeleteKategori(Kategori instance);
    partial void InsertKullanici(Kullanici instance);
    partial void UpdateKullanici(Kullanici instance);
    partial void DeleteKullanici(Kullanici instance);
    partial void InsertMakale(Makale instance);
    partial void UpdateMakale(Makale instance);
    partial void DeleteMakale(Makale instance);
    partial void InsertLog(Log instance);
    partial void UpdateLog(Log instance);
    partial void DeleteLog(Log instance);
    partial void InsertYorum(Yorum instance);
    partial void UpdateYorum(Yorum instance);
    partial void DeleteYorum(Yorum instance);
    #endregion
		
		public BlogDataContext() : 
				base(global::DAL.Properties.Settings.Default.KisiselBlogConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Etiket> Etikets
		{
			get
			{
				return this.GetTable<Etiket>();
			}
		}
		
		public System.Data.Linq.Table<EtiketMakale> EtiketMakales
		{
			get
			{
				return this.GetTable<EtiketMakale>();
			}
		}
		
		public System.Data.Linq.Table<Iletisim> Iletisims
		{
			get
			{
				return this.GetTable<Iletisim>();
			}
		}
		
		public System.Data.Linq.Table<Kategori> Kategoris
		{
			get
			{
				return this.GetTable<Kategori>();
			}
		}
		
		public System.Data.Linq.Table<Kullanici> Kullanicis
		{
			get
			{
				return this.GetTable<Kullanici>();
			}
		}
		
		public System.Data.Linq.Table<Makale> Makales
		{
			get
			{
				return this.GetTable<Makale>();
			}
		}
		
		public System.Data.Linq.Table<Log> Logs
		{
			get
			{
				return this.GetTable<Log>();
			}
		}
		
		public System.Data.Linq.Table<Yorum> Yorums
		{
			get
			{
				return this.GetTable<Yorum>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Etiket")]
	public partial class Etiket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EtiketId;
		
		private string _Ad;
		
		private EntitySet<EtiketMakale> _EtiketMakales;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEtiketIdChanging(int value);
    partial void OnEtiketIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    #endregion
		
		public Etiket()
		{
			this._EtiketMakales = new EntitySet<EtiketMakale>(new Action<EtiketMakale>(this.attach_EtiketMakales), new Action<EtiketMakale>(this.detach_EtiketMakales));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EtiketId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EtiketId
		{
			get
			{
				return this._EtiketId;
			}
			set
			{
				if ((this._EtiketId != value))
				{
					this.OnEtiketIdChanging(value);
					this.SendPropertyChanging();
					this._EtiketId = value;
					this.SendPropertyChanged("EtiketId");
					this.OnEtiketIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Etiket_EtiketMakale", Storage="_EtiketMakales", ThisKey="EtiketId", OtherKey="EtiketId")]
		public EntitySet<EtiketMakale> EtiketMakales
		{
			get
			{
				return this._EtiketMakales;
			}
			set
			{
				this._EtiketMakales.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EtiketMakales(EtiketMakale entity)
		{
			this.SendPropertyChanging();
			entity.Etiket = this;
		}
		
		private void detach_EtiketMakales(EtiketMakale entity)
		{
			this.SendPropertyChanging();
			entity.Etiket = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EtiketMakale")]
	public partial class EtiketMakale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EtiketMakaleID;
		
		private int _EtiketId;
		
		private int _MakaleId;
		
		private EntityRef<Etiket> _Etiket;
		
		private EntityRef<Makale> _Makale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEtiketMakaleIDChanging(int value);
    partial void OnEtiketMakaleIDChanged();
    partial void OnEtiketIdChanging(int value);
    partial void OnEtiketIdChanged();
    partial void OnMakaleIdChanging(int value);
    partial void OnMakaleIdChanged();
    #endregion
		
		public EtiketMakale()
		{
			this._Etiket = default(EntityRef<Etiket>);
			this._Makale = default(EntityRef<Makale>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EtiketMakaleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EtiketMakaleID
		{
			get
			{
				return this._EtiketMakaleID;
			}
			set
			{
				if ((this._EtiketMakaleID != value))
				{
					this.OnEtiketMakaleIDChanging(value);
					this.SendPropertyChanging();
					this._EtiketMakaleID = value;
					this.SendPropertyChanged("EtiketMakaleID");
					this.OnEtiketMakaleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EtiketId", DbType="Int NOT NULL")]
		public int EtiketId
		{
			get
			{
				return this._EtiketId;
			}
			set
			{
				if ((this._EtiketId != value))
				{
					if (this._Etiket.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEtiketIdChanging(value);
					this.SendPropertyChanging();
					this._EtiketId = value;
					this.SendPropertyChanged("EtiketId");
					this.OnEtiketIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MakaleId", DbType="Int NOT NULL")]
		public int MakaleId
		{
			get
			{
				return this._MakaleId;
			}
			set
			{
				if ((this._MakaleId != value))
				{
					if (this._Makale.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakaleIdChanging(value);
					this.SendPropertyChanging();
					this._MakaleId = value;
					this.SendPropertyChanged("MakaleId");
					this.OnMakaleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Etiket_EtiketMakale", Storage="_Etiket", ThisKey="EtiketId", OtherKey="EtiketId", IsForeignKey=true)]
		public Etiket Etiket
		{
			get
			{
				return this._Etiket.Entity;
			}
			set
			{
				Etiket previousValue = this._Etiket.Entity;
				if (((previousValue != value) 
							|| (this._Etiket.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Etiket.Entity = null;
						previousValue.EtiketMakales.Remove(this);
					}
					this._Etiket.Entity = value;
					if ((value != null))
					{
						value.EtiketMakales.Add(this);
						this._EtiketId = value.EtiketId;
					}
					else
					{
						this._EtiketId = default(int);
					}
					this.SendPropertyChanged("Etiket");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Makale_EtiketMakale", Storage="_Makale", ThisKey="MakaleId", OtherKey="MakaleId", IsForeignKey=true)]
		public Makale Makale
		{
			get
			{
				return this._Makale.Entity;
			}
			set
			{
				Makale previousValue = this._Makale.Entity;
				if (((previousValue != value) 
							|| (this._Makale.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Makale.Entity = null;
						previousValue.EtiketMakales.Remove(this);
					}
					this._Makale.Entity = value;
					if ((value != null))
					{
						value.EtiketMakales.Add(this);
						this._MakaleId = value.MakaleId;
					}
					else
					{
						this._MakaleId = default(int);
					}
					this.SendPropertyChanged("Makale");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Iletisim")]
	public partial class Iletisim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IletisimId;
		
		private string _Eposta;
		
		private string _Ad;
		
		private string _Soyad;
		
		private System.DateTime _Tarih;
		
		private string _Icerik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIletisimIdChanging(int value);
    partial void OnIletisimIdChanged();
    partial void OnEpostaChanging(string value);
    partial void OnEpostaChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnIcerikChanging(string value);
    partial void OnIcerikChanged();
    #endregion
		
		public Iletisim()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IletisimId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IletisimId
		{
			get
			{
				return this._IletisimId;
			}
			set
			{
				if ((this._IletisimId != value))
				{
					this.OnIletisimIdChanging(value);
					this.SendPropertyChanging();
					this._IletisimId = value;
					this.SendPropertyChanged("IletisimId");
					this.OnIletisimIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eposta", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Eposta
		{
			get
			{
				return this._Eposta;
			}
			set
			{
				if ((this._Eposta != value))
				{
					this.OnEpostaChanging(value);
					this.SendPropertyChanging();
					this._Eposta = value;
					this.SendPropertyChanged("Eposta");
					this.OnEpostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icerik", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Icerik
		{
			get
			{
				return this._Icerik;
			}
			set
			{
				if ((this._Icerik != value))
				{
					this.OnIcerikChanging(value);
					this.SendPropertyChanging();
					this._Icerik = value;
					this.SendPropertyChanged("Icerik");
					this.OnIcerikChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategori")]
	public partial class Kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KategoriId;
		
		private string _KategoriAd;
		
		private bool _Deleted;
		
		private EntitySet<Makale> _Makales;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKategoriIdChanging(int value);
    partial void OnKategoriIdChanged();
    partial void OnKategoriAdChanging(string value);
    partial void OnKategoriAdChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Kategori()
		{
			this._Makales = new EntitySet<Makale>(new Action<Makale>(this.attach_Makales), new Action<Makale>(this.detach_Makales));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KategoriId
		{
			get
			{
				return this._KategoriId;
			}
			set
			{
				if ((this._KategoriId != value))
				{
					this.OnKategoriIdChanging(value);
					this.SendPropertyChanging();
					this._KategoriId = value;
					this.SendPropertyChanged("KategoriId");
					this.OnKategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriAd", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string KategoriAd
		{
			get
			{
				return this._KategoriAd;
			}
			set
			{
				if ((this._KategoriAd != value))
				{
					this.OnKategoriAdChanging(value);
					this.SendPropertyChanging();
					this._KategoriAd = value;
					this.SendPropertyChanged("KategoriAd");
					this.OnKategoriAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Makale", Storage="_Makales", ThisKey="KategoriId", OtherKey="KategoriId")]
		public EntitySet<Makale> Makales
		{
			get
			{
				return this._Makales;
			}
			set
			{
				this._Makales.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Makales(Makale entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = this;
		}
		
		private void detach_Makales(Makale entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanici")]
	public partial class Kullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KullaniciId;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _EPosta;
		
		private string _Sifre;
		
		private System.Nullable<bool> _Rol;
		
		private System.DateTime _SonGirisTarihi;
		
		private string _SonIP;
		
		private string _SonTarayici;
		
		private bool _Deleted;
		
		private string _GUID;
		
		private EntitySet<Makale> _Makales;
		
		private EntitySet<Yorum> _Yorums;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKullaniciIdChanging(int value);
    partial void OnKullaniciIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnEPostaChanging(string value);
    partial void OnEPostaChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnRolChanging(System.Nullable<bool> value);
    partial void OnRolChanged();
    partial void OnSonGirisTarihiChanging(System.DateTime value);
    partial void OnSonGirisTarihiChanged();
    partial void OnSonIPChanging(string value);
    partial void OnSonIPChanged();
    partial void OnSonTarayiciChanging(string value);
    partial void OnSonTarayiciChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnGUIDChanging(string value);
    partial void OnGUIDChanged();
    #endregion
		
		public Kullanici()
		{
			this._Makales = new EntitySet<Makale>(new Action<Makale>(this.attach_Makales), new Action<Makale>(this.detach_Makales));
			this._Yorums = new EntitySet<Yorum>(new Action<Yorum>(this.attach_Yorums), new Action<Yorum>(this.detach_Yorums));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KullaniciId
		{
			get
			{
				return this._KullaniciId;
			}
			set
			{
				if ((this._KullaniciId != value))
				{
					this.OnKullaniciIdChanging(value);
					this.SendPropertyChanging();
					this._KullaniciId = value;
					this.SendPropertyChanged("KullaniciId");
					this.OnKullaniciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPosta", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EPosta
		{
			get
			{
				return this._EPosta;
			}
			set
			{
				if ((this._EPosta != value))
				{
					this.OnEPostaChanging(value);
					this.SendPropertyChanging();
					this._EPosta = value;
					this.SendPropertyChanged("EPosta");
					this.OnEPostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Bit")]
		public System.Nullable<bool> Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SonGirisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime SonGirisTarihi
		{
			get
			{
				return this._SonGirisTarihi;
			}
			set
			{
				if ((this._SonGirisTarihi != value))
				{
					this.OnSonGirisTarihiChanging(value);
					this.SendPropertyChanging();
					this._SonGirisTarihi = value;
					this.SendPropertyChanged("SonGirisTarihi");
					this.OnSonGirisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SonIP", DbType="NVarChar(50)")]
		public string SonIP
		{
			get
			{
				return this._SonIP;
			}
			set
			{
				if ((this._SonIP != value))
				{
					this.OnSonIPChanging(value);
					this.SendPropertyChanging();
					this._SonIP = value;
					this.SendPropertyChanged("SonIP");
					this.OnSonIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SonTarayici", DbType="NVarChar(50)")]
		public string SonTarayici
		{
			get
			{
				return this._SonTarayici;
			}
			set
			{
				if ((this._SonTarayici != value))
				{
					this.OnSonTarayiciChanging(value);
					this.SendPropertyChanging();
					this._SonTarayici = value;
					this.SendPropertyChanged("SonTarayici");
					this.OnSonTarayiciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="NVarChar(250)")]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Makale", Storage="_Makales", ThisKey="KullaniciId", OtherKey="KullaniciId")]
		public EntitySet<Makale> Makales
		{
			get
			{
				return this._Makales;
			}
			set
			{
				this._Makales.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Yorum", Storage="_Yorums", ThisKey="KullaniciId", OtherKey="KullaniciId")]
		public EntitySet<Yorum> Yorums
		{
			get
			{
				return this._Yorums;
			}
			set
			{
				this._Yorums.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Makales(Makale entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = this;
		}
		
		private void detach_Makales(Makale entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = null;
		}
		
		private void attach_Yorums(Yorum entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = this;
		}
		
		private void detach_Yorums(Yorum entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Makale")]
	public partial class Makale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MakaleId;
		
		private int _KullaniciId;
		
		private int _KategoriId;
		
		private string _Baslik;
		
		private string _MakaleYazi;
		
		private System.DateTime _Tarih;
		
		private string _Gorsel;
		
		private bool _HaberMi;
		
		private bool _Deleted;
		
		private EntitySet<EtiketMakale> _EtiketMakales;
		
		private EntitySet<Yorum> _Yorums;
		
		private EntityRef<Kategori> _Kategori;
		
		private EntityRef<Kullanici> _Kullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMakaleIdChanging(int value);
    partial void OnMakaleIdChanged();
    partial void OnKullaniciIdChanging(int value);
    partial void OnKullaniciIdChanged();
    partial void OnKategoriIdChanging(int value);
    partial void OnKategoriIdChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnMakaleYaziChanging(string value);
    partial void OnMakaleYaziChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnGorselChanging(string value);
    partial void OnGorselChanged();
    partial void OnHaberMiChanging(bool value);
    partial void OnHaberMiChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Makale()
		{
			this._EtiketMakales = new EntitySet<EtiketMakale>(new Action<EtiketMakale>(this.attach_EtiketMakales), new Action<EtiketMakale>(this.detach_EtiketMakales));
			this._Yorums = new EntitySet<Yorum>(new Action<Yorum>(this.attach_Yorums), new Action<Yorum>(this.detach_Yorums));
			this._Kategori = default(EntityRef<Kategori>);
			this._Kullanici = default(EntityRef<Kullanici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MakaleId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MakaleId
		{
			get
			{
				return this._MakaleId;
			}
			set
			{
				if ((this._MakaleId != value))
				{
					this.OnMakaleIdChanging(value);
					this.SendPropertyChanging();
					this._MakaleId = value;
					this.SendPropertyChanged("MakaleId");
					this.OnMakaleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciId", DbType="Int NOT NULL")]
		public int KullaniciId
		{
			get
			{
				return this._KullaniciId;
			}
			set
			{
				if ((this._KullaniciId != value))
				{
					if (this._Kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKullaniciIdChanging(value);
					this.SendPropertyChanging();
					this._KullaniciId = value;
					this.SendPropertyChanged("KullaniciId");
					this.OnKullaniciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriId", DbType="Int NOT NULL")]
		public int KategoriId
		{
			get
			{
				return this._KategoriId;
			}
			set
			{
				if ((this._KategoriId != value))
				{
					if (this._Kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIdChanging(value);
					this.SendPropertyChanging();
					this._KategoriId = value;
					this.SendPropertyChanged("KategoriId");
					this.OnKategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MakaleYazi", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MakaleYazi
		{
			get
			{
				return this._MakaleYazi;
			}
			set
			{
				if ((this._MakaleYazi != value))
				{
					this.OnMakaleYaziChanging(value);
					this.SendPropertyChanging();
					this._MakaleYazi = value;
					this.SendPropertyChanged("MakaleYazi");
					this.OnMakaleYaziChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gorsel", DbType="NVarChar(50)")]
		public string Gorsel
		{
			get
			{
				return this._Gorsel;
			}
			set
			{
				if ((this._Gorsel != value))
				{
					this.OnGorselChanging(value);
					this.SendPropertyChanging();
					this._Gorsel = value;
					this.SendPropertyChanged("Gorsel");
					this.OnGorselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberMi", DbType="Bit NOT NULL")]
		public bool HaberMi
		{
			get
			{
				return this._HaberMi;
			}
			set
			{
				if ((this._HaberMi != value))
				{
					this.OnHaberMiChanging(value);
					this.SendPropertyChanging();
					this._HaberMi = value;
					this.SendPropertyChanged("HaberMi");
					this.OnHaberMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Makale_EtiketMakale", Storage="_EtiketMakales", ThisKey="MakaleId", OtherKey="MakaleId")]
		public EntitySet<EtiketMakale> EtiketMakales
		{
			get
			{
				return this._EtiketMakales;
			}
			set
			{
				this._EtiketMakales.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Makale_Yorum", Storage="_Yorums", ThisKey="MakaleId", OtherKey="MakaleId")]
		public EntitySet<Yorum> Yorums
		{
			get
			{
				return this._Yorums;
			}
			set
			{
				this._Yorums.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Makale", Storage="_Kategori", ThisKey="KategoriId", OtherKey="KategoriId", IsForeignKey=true)]
		public Kategori Kategori
		{
			get
			{
				return this._Kategori.Entity;
			}
			set
			{
				Kategori previousValue = this._Kategori.Entity;
				if (((previousValue != value) 
							|| (this._Kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategori.Entity = null;
						previousValue.Makales.Remove(this);
					}
					this._Kategori.Entity = value;
					if ((value != null))
					{
						value.Makales.Add(this);
						this._KategoriId = value.KategoriId;
					}
					else
					{
						this._KategoriId = default(int);
					}
					this.SendPropertyChanged("Kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Makale", Storage="_Kullanici", ThisKey="KullaniciId", OtherKey="KullaniciId", IsForeignKey=true)]
		public Kullanici Kullanici
		{
			get
			{
				return this._Kullanici.Entity;
			}
			set
			{
				Kullanici previousValue = this._Kullanici.Entity;
				if (((previousValue != value) 
							|| (this._Kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kullanici.Entity = null;
						previousValue.Makales.Remove(this);
					}
					this._Kullanici.Entity = value;
					if ((value != null))
					{
						value.Makales.Add(this);
						this._KullaniciId = value.KullaniciId;
					}
					else
					{
						this._KullaniciId = default(int);
					}
					this.SendPropertyChanged("Kullanici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EtiketMakales(EtiketMakale entity)
		{
			this.SendPropertyChanging();
			entity.Makale = this;
		}
		
		private void detach_EtiketMakales(EtiketMakale entity)
		{
			this.SendPropertyChanging();
			entity.Makale = null;
		}
		
		private void attach_Yorums(Yorum entity)
		{
			this.SendPropertyChanging();
			entity.Makale = this;
		}
		
		private void detach_Yorums(Yorum entity)
		{
			this.SendPropertyChanging();
			entity.Makale = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Log]")]
	public partial class Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogId;
		
		private int _KullaniciID;
		
		private System.DateTime _IslemTarihi;
		
		private byte _IslemTuru;
		
		private string _IslemAciklama;
		
		private string _IP;
		
		private string _Tarayici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIdChanging(int value);
    partial void OnLogIdChanged();
    partial void OnKullaniciIDChanging(int value);
    partial void OnKullaniciIDChanged();
    partial void OnIslemTarihiChanging(System.DateTime value);
    partial void OnIslemTarihiChanged();
    partial void OnIslemTuruChanging(byte value);
    partial void OnIslemTuruChanged();
    partial void OnIslemAciklamaChanging(string value);
    partial void OnIslemAciklamaChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnTarayiciChanging(string value);
    partial void OnTarayiciChanged();
    #endregion
		
		public Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogId
		{
			get
			{
				return this._LogId;
			}
			set
			{
				if ((this._LogId != value))
				{
					this.OnLogIdChanging(value);
					this.SendPropertyChanging();
					this._LogId = value;
					this.SendPropertyChanged("LogId");
					this.OnLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciID", DbType="Int NOT NULL")]
		public int KullaniciID
		{
			get
			{
				return this._KullaniciID;
			}
			set
			{
				if ((this._KullaniciID != value))
				{
					this.OnKullaniciIDChanging(value);
					this.SendPropertyChanging();
					this._KullaniciID = value;
					this.SendPropertyChanged("KullaniciID");
					this.OnKullaniciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime IslemTarihi
		{
			get
			{
				return this._IslemTarihi;
			}
			set
			{
				if ((this._IslemTarihi != value))
				{
					this.OnIslemTarihiChanging(value);
					this.SendPropertyChanging();
					this._IslemTarihi = value;
					this.SendPropertyChanged("IslemTarihi");
					this.OnIslemTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemTuru", DbType="TinyInt NOT NULL")]
		public byte IslemTuru
		{
			get
			{
				return this._IslemTuru;
			}
			set
			{
				if ((this._IslemTuru != value))
				{
					this.OnIslemTuruChanging(value);
					this.SendPropertyChanging();
					this._IslemTuru = value;
					this.SendPropertyChanged("IslemTuru");
					this.OnIslemTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemAciklama", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string IslemAciklama
		{
			get
			{
				return this._IslemAciklama;
			}
			set
			{
				if ((this._IslemAciklama != value))
				{
					this.OnIslemAciklamaChanging(value);
					this.SendPropertyChanging();
					this._IslemAciklama = value;
					this.SendPropertyChanged("IslemAciklama");
					this.OnIslemAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarayici", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tarayici
		{
			get
			{
				return this._Tarayici;
			}
			set
			{
				if ((this._Tarayici != value))
				{
					this.OnTarayiciChanging(value);
					this.SendPropertyChanging();
					this._Tarayici = value;
					this.SendPropertyChanged("Tarayici");
					this.OnTarayiciChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yorum")]
	public partial class Yorum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YorumId;
		
		private string _YorumText;
		
		private int _MakaleId;
		
		private int _KullaniciId;
		
		private System.DateTime _Tarih;
		
		private System.Nullable<int> _Begeni;
		
		private bool _Deleted;
		
		private EntityRef<Kullanici> _Kullanici;
		
		private EntityRef<Makale> _Makale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYorumIdChanging(int value);
    partial void OnYorumIdChanged();
    partial void OnYorumTextChanging(string value);
    partial void OnYorumTextChanged();
    partial void OnMakaleIdChanging(int value);
    partial void OnMakaleIdChanged();
    partial void OnKullaniciIdChanging(int value);
    partial void OnKullaniciIdChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnBegeniChanging(System.Nullable<int> value);
    partial void OnBegeniChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Yorum()
		{
			this._Kullanici = default(EntityRef<Kullanici>);
			this._Makale = default(EntityRef<Makale>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YorumId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YorumId
		{
			get
			{
				return this._YorumId;
			}
			set
			{
				if ((this._YorumId != value))
				{
					this.OnYorumIdChanging(value);
					this.SendPropertyChanging();
					this._YorumId = value;
					this.SendPropertyChanged("YorumId");
					this.OnYorumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YorumText", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string YorumText
		{
			get
			{
				return this._YorumText;
			}
			set
			{
				if ((this._YorumText != value))
				{
					this.OnYorumTextChanging(value);
					this.SendPropertyChanging();
					this._YorumText = value;
					this.SendPropertyChanged("YorumText");
					this.OnYorumTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MakaleId", DbType="Int NOT NULL")]
		public int MakaleId
		{
			get
			{
				return this._MakaleId;
			}
			set
			{
				if ((this._MakaleId != value))
				{
					if (this._Makale.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakaleIdChanging(value);
					this.SendPropertyChanging();
					this._MakaleId = value;
					this.SendPropertyChanged("MakaleId");
					this.OnMakaleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciId", DbType="Int NOT NULL")]
		public int KullaniciId
		{
			get
			{
				return this._KullaniciId;
			}
			set
			{
				if ((this._KullaniciId != value))
				{
					if (this._Kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKullaniciIdChanging(value);
					this.SendPropertyChanging();
					this._KullaniciId = value;
					this.SendPropertyChanged("KullaniciId");
					this.OnKullaniciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Begeni", DbType="Int")]
		public System.Nullable<int> Begeni
		{
			get
			{
				return this._Begeni;
			}
			set
			{
				if ((this._Begeni != value))
				{
					this.OnBegeniChanging(value);
					this.SendPropertyChanging();
					this._Begeni = value;
					this.SendPropertyChanged("Begeni");
					this.OnBegeniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Yorum", Storage="_Kullanici", ThisKey="KullaniciId", OtherKey="KullaniciId", IsForeignKey=true)]
		public Kullanici Kullanici
		{
			get
			{
				return this._Kullanici.Entity;
			}
			set
			{
				Kullanici previousValue = this._Kullanici.Entity;
				if (((previousValue != value) 
							|| (this._Kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kullanici.Entity = null;
						previousValue.Yorums.Remove(this);
					}
					this._Kullanici.Entity = value;
					if ((value != null))
					{
						value.Yorums.Add(this);
						this._KullaniciId = value.KullaniciId;
					}
					else
					{
						this._KullaniciId = default(int);
					}
					this.SendPropertyChanged("Kullanici");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Makale_Yorum", Storage="_Makale", ThisKey="MakaleId", OtherKey="MakaleId", IsForeignKey=true)]
		public Makale Makale
		{
			get
			{
				return this._Makale.Entity;
			}
			set
			{
				Makale previousValue = this._Makale.Entity;
				if (((previousValue != value) 
							|| (this._Makale.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Makale.Entity = null;
						previousValue.Yorums.Remove(this);
					}
					this._Makale.Entity = value;
					if ((value != null))
					{
						value.Yorums.Add(this);
						this._MakaleId = value.MakaleId;
					}
					else
					{
						this._MakaleId = default(int);
					}
					this.SendPropertyChanged("Makale");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
